engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/
- test/
- docs/
- coverage/
- .git-standards/
