language: node_js
node_js:
- '4.2'
- '4.3'
- '5.6'
- iojs
addons:
  secure: JLfjw+5aZBOXS7b7D3vaijL3vd9v2EF+p5H9qQoElLkyjcVqRYYz5DvWQ+4H8QzeZ+bGHhiYZe7tAJqXaSF1JOjTOl/kVJ+DSHRsYEnpzTA5OtCceZ6vbSrzpC1Xup/6uFdxq+KHTtWO/O/3SdGvQXCezfR6kOp8pkQYCu/viPz0G34pERRwkvZxZ1pyUrchJY1GSX2eoqqCiQcuicJndqg7zyZlaEqLwdjTVQV4E50xVQKICWd5mcyRtV5LsTE5VfInoaBdaHFhsibk9LLRxCJrtNYoE+C6R4lvxAl2dDg6/Ajv2LCZiaV1L+x7znDnNgXUE3Ac7Y54G46MzQXShsoKa7vCy8sQZ8o/xZzyzhBxJ8rsfPTj6zsravgbEKtr47pl78eG35m6SujqjHzMYWIaxaqpcT406b9p+CXf7GfM3E0RUTMD/WwX9dxDJrU2T2bXhim5LHHH1WBuBfmVdPo/7xcQPN73B8IoJE/xbaWfJS+t0E5+K7BzcQwLxO5IXfiW84BuJ7/MQq5FuVgaOgMip4nZRLufJ9ZzqaIgztJlEiIOFnZ/QKDO2jhmAwFz6FJtSVbrAfBElF6iyKYkD30nlmA97GadiN4WFUxPm4BsjczqmpG+ajpi2n/kqns9tHdQxB+A58QFPLm6Ft9RMiaTa/MXzBftipKxc7vg/4Y=
